# Generated by Django 4.1.3 on 2022-11-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
